package com.canonal.periodictable

import com.canonal.periodictable.model.Element

object Data {
    fun getDummyData(): List<Element>{
        val elementList: ArrayList<Element> = arrayListOf()

        val hydrogen = Element("hydrogen","H",1,"Nonmetal")
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)
        elementList.add(hydrogen)



        return elementList
    }
}