package com.canonal.periodictable

import com.canonal.periodictable.model.ElementModel
import com.canonal.periodictable.model.ElementType
import com.canonal.periodictable.model.EmptyModel
import com.canonal.periodictable.model.PeriodicTableModel

object Data {
    fun getDummyData(): List<PeriodicTableModel> {
        //9x18=162 elements in full table
        //118 actual elements in periodic table
        //create 162 objects with two model types
        //ElementModel will consist data whereas EmptyModel
        //consist no data or UI

        val elementList: ArrayList<PeriodicTableModel> = arrayListOf()

        val element1 = ElementModel("Hydrogen", "H", 1, ElementType.NONMETAL, 1)
        val element2 = EmptyModel(fullTableNumber = 2)
        val element3 = EmptyModel(fullTableNumber = 3)
        val element4 = EmptyModel(fullTableNumber = 4)
        val element5 = EmptyModel(fullTableNumber = 5)
        val element6 = EmptyModel(fullTableNumber = 6)
        val element7 = EmptyModel(fullTableNumber = 7)
        val element8 = EmptyModel(fullTableNumber = 8)
        val element9 = EmptyModel(fullTableNumber = 9)
        val element10 = EmptyModel(fullTableNumber = 10)
        val element11 = EmptyModel(fullTableNumber = 11)
        val element12 = EmptyModel(fullTableNumber = 12)
        val element13 = EmptyModel(fullTableNumber = 13)
        val element14 = EmptyModel(fullTableNumber = 14)
        val element15 = EmptyModel(fullTableNumber = 15)
        val element16 = EmptyModel(fullTableNumber = 16)
        val element17 = EmptyModel(fullTableNumber = 17)
        val element18 = ElementModel("Helium", "He", 2, ElementType.NOBLE_GAS, 18)
        val element19 = ElementModel("Lithium", "Li", 3, ElementType.ALKALI_METAL, 19)
        val element20 = ElementModel("Beryllium", "Be", 4, ElementType.ALKALINE_EARTH_METAL, 20)
        val element21 = EmptyModel(fullTableNumber = 21)
        val element22 = EmptyModel(fullTableNumber = 22)
        val element23 = EmptyModel(fullTableNumber = 23)
        val element24 = EmptyModel(fullTableNumber = 24)
        val element25 = EmptyModel(fullTableNumber = 25)
        val element26 = EmptyModel(fullTableNumber = 26)
        val element27 = EmptyModel(fullTableNumber = 27)
        val element28 = EmptyModel(fullTableNumber = 28)
        val element29 = EmptyModel(fullTableNumber = 29)
        val element30 = EmptyModel(fullTableNumber = 30)
        val element31 = ElementModel("Boron", "B", 5, ElementType.METALLOID, 31)
        val element32 = ElementModel("Carbon", "C", 6, ElementType.NONMETAL, 32)
        val element33 = ElementModel("Nitrogen", "N", 7, ElementType.NONMETAL, 33)
        val element34 = ElementModel("Oxygen", "O", 8, ElementType.NONMETAL, 34)
        val element35 = ElementModel("Fluorine", "F", 9, ElementType.HALOGEN, 35)
        val element36 = ElementModel("Neon", "NE", 10, ElementType.NOBLE_GAS, 36)
        val element37 = ElementModel("Sodium", "Na", 11, ElementType.ALKALI_METAL, 37)
        val element38 = ElementModel("Magnesium", "Mg", 12, ElementType.ALKALINE_EARTH_METAL, 38)
        val element39 = EmptyModel(fullTableNumber = 39)
        val element40 = EmptyModel(fullTableNumber = 40)
        val element41 = EmptyModel(fullTableNumber = 41)
        val element42 = EmptyModel(fullTableNumber = 42)
        val element43 = EmptyModel(fullTableNumber = 43)
        val element44 = EmptyModel(fullTableNumber = 44)
        val element45 = EmptyModel(fullTableNumber = 45)
        val element46 = EmptyModel(fullTableNumber = 46)
        val element47 = EmptyModel(fullTableNumber = 47)
        val element48 = EmptyModel(fullTableNumber = 48)
        val element49 = ElementModel("Aluminum", "Al", 13, ElementType.POST_TRANSITION_METAL, 49)
        val element50 = ElementModel("Silicon", "Si", 14, ElementType.METALLOID, 50)
        val element51 = ElementModel("Phosphorus", "P", 15, ElementType.NONMETAL, 51)
        val element52 = ElementModel("Sulfur", "S", 16, ElementType.NONMETAL, 52)
        val element53 = ElementModel("Chlorine", "Cl", 17, ElementType.HALOGEN, 53)
        val element54 = ElementModel("Argon", "Ar", 18, ElementType.NOBLE_GAS, 54)
        val element55 = ElementModel("Potassium", "K", 19, ElementType.ALKALI_METAL, 55)
        val element56 = ElementModel("Calcium", "Ca", 20, ElementType.ALKALINE_EARTH_METAL, 56)
        val element57 = ElementModel("Scandium", "Sc", 21, ElementType.TRANSITION_METAL, 57)
        val element58 = ElementModel("Titanium", "Ti", 22, ElementType.TRANSITION_METAL, 58)
        val element59 = ElementModel("Vanadium", "V", 23, ElementType.TRANSITION_METAL, 59)
        val element60 = ElementModel("Chromium", "Cr", 24, ElementType.TRANSITION_METAL, 60)
        val element61 = ElementModel("Manganese", "Mn", 25, ElementType.TRANSITION_METAL, 61)
        val element62 = ElementModel("Iron", "Fe", 26, ElementType.TRANSITION_METAL, 62)
        val element63 = ElementModel("Cobalt", "Co", 27, ElementType.TRANSITION_METAL, 63)
        val element64 = ElementModel("Nickel", "Ni", 28, ElementType.TRANSITION_METAL, 64)
        val element65 = ElementModel("Copper", "Cu", 29, ElementType.TRANSITION_METAL, 65)
        val element66 = ElementModel("Zinc", "Zn", 30, ElementType.TRANSITION_METAL, 66)
        val element67 = ElementModel("Gallium", "Ga", 31, ElementType.POST_TRANSITION_METAL, 67)
        val element68 = ElementModel("Germanium", "Ge", 32, ElementType.METALLOID, 68)
        val element69 = ElementModel("Arsenic", "As", 33, ElementType.METALLOID, 69)
        val element70 = ElementModel("Selenium", "Se", 34, ElementType.NONMETAL, 70)
        val element71 = ElementModel("Bromine", "Br", 35, ElementType.HALOGEN, 71)
        val element72 = ElementModel("Krypton", "Kr", 36, ElementType.NOBLE_GAS, 72)
        val element73 = ElementModel("Rubidium", "Rb", 37, ElementType.ALKALI_METAL, 73)
        val element74 = ElementModel("Strontium", "Sr", 38, ElementType.ALKALINE_EARTH_METAL, 74)
        val element75 = ElementModel("Yttrium", "Y", 39, ElementType.TRANSITION_METAL, 75)
        val element76 = ElementModel("Zirconium", "Zr", 40, ElementType.TRANSITION_METAL, 76)
        val element77 = ElementModel("Niobium", "Nb", 41, ElementType.TRANSITION_METAL, 77)
        val element78 = ElementModel("Molybdenum", "Mo", 42, ElementType.TRANSITION_METAL, 78)
        val element79 = ElementModel("Technetium", "Tc", 43, ElementType.TRANSITION_METAL, 79)
        val element80 = ElementModel("Ruthenium", "Ru", 44, ElementType.TRANSITION_METAL, 80)
        val element81 = ElementModel("Rhodium", "Rh", 45, ElementType.TRANSITION_METAL, 81)
        val element82 = ElementModel("Palladium", "Pd", 46, ElementType.TRANSITION_METAL, 82)
        val element83 = ElementModel("Silver", "Ag", 47, ElementType.TRANSITION_METAL, 83)
        val element84 = ElementModel("Cadmium", "Cd", 48, ElementType.TRANSITION_METAL, 84)
        val element85 = ElementModel("Indium", "In", 49, ElementType.POST_TRANSITION_METAL, 85)
        val element86 = ElementModel("Tin", "Sn", 50, ElementType.POST_TRANSITION_METAL, 86)
        val element87 = ElementModel("Antimony", "Sb", 51, ElementType.METALLOID, 87)
        val element88 = ElementModel("Tellurium", "Te", 52, ElementType.METALLOID, 88)
        val element89 = ElementModel("Iodine", "I", 53, ElementType.HALOGEN, 89)
        val element90 = ElementModel("Xenon", "Xe", 54, ElementType.NOBLE_GAS, 90)
        val element91 = ElementModel("Cesium", "Cs", 55, ElementType.ALKALI_METAL, 91)
        val element92 = ElementModel("Barium", "Ba", 56, ElementType.ALKALINE_EARTH_METAL, 92)
        val element93 = EmptyModel(fullTableNumber = 93)
        val element94 = ElementModel("Hafnium", "Hf", 72, ElementType.TRANSITION_METAL, 94)
        val element95 = ElementModel("Tantalum", "Ta", 73, ElementType.TRANSITION_METAL, 95)
        val element96 = ElementModel("Tungsten", "W", 74, ElementType.TRANSITION_METAL, 96)
        val element97 = ElementModel("Rhenium", "Re", 75, ElementType.TRANSITION_METAL, 97)
        val element98 = ElementModel("Osmium", "Os", 76, ElementType.TRANSITION_METAL, 98)
        val element99 = ElementModel("Iridium", "Ir", 77, ElementType.TRANSITION_METAL, 99)
        val element100 = ElementModel("Platinum", "Pt", 78, ElementType.TRANSITION_METAL, 100)
        val element101 = ElementModel("Gold", "Au", 79, ElementType.TRANSITION_METAL, 101)
        val element102 = ElementModel("Mercury", "Hg", 80, ElementType.TRANSITION_METAL, 102)
        val element103 = ElementModel("Thallium", "Tl", 81, ElementType.POST_TRANSITION_METAL, 103)
        val element104 = ElementModel("Lead", "Pb", 82, ElementType.POST_TRANSITION_METAL, 104)
        val element105 = ElementModel("Bismuth", "Bi", 83, ElementType.POST_TRANSITION_METAL, 105)
        val element106 = ElementModel("Polonium", "Po", 84, ElementType.METALLOID, 106)
        val element107 = ElementModel("Astatine", "At", 85, ElementType.HALOGEN, 107)
        val element108 = ElementModel("Radon", "Rn", 86, ElementType.NOBLE_GAS, 108)
        val element109 = ElementModel("Francium", "Fr", 87, ElementType.ALKALI_METAL, 109)
        val element110 = ElementModel("Radium", "Ra", 88, ElementType.ALKALINE_EARTH_METAL, 110)
        val element111 = EmptyModel(fullTableNumber = 111)
        val element112 =
            ElementModel("Rutherfordium", "Rf", 104, ElementType.TRANSITION_METAL, 112)
        val element113 = ElementModel("Dubnium", "Dd", 105, ElementType.TRANSITION_METAL, 113)
        val element114 = ElementModel("Seaborgium", "Sg", 106, ElementType.TRANSITION_METAL, 114)
        val element115 = ElementModel("Bohrium", "Bh", 107, ElementType.TRANSITION_METAL, 115)
        val element116 = ElementModel("Hassium", "Hs", 108, ElementType.TRANSITION_METAL, 116)
        val element117 = ElementModel("Meitnerium", "Mt", 109, ElementType.TRANSITION_METAL, 117)
        val element118 = ElementModel("Darmstadtium", "Ds", 110, ElementType.TRANSITION_METAL, 118)
        val element119 = ElementModel("Roentgenium", "Rg", 111, ElementType.TRANSITION_METAL, 119)
        val element120 = ElementModel("Ununbium", "Uub", 112, ElementType.TRANSITION_METAL, 120)
        val element121 =
            ElementModel("Ununtrium", "Uut", 113, ElementType.POST_TRANSITION_METAL, 121)
        val element122 =
            ElementModel("Ununquadium", "Uuq", 114, ElementType.POST_TRANSITION_METAL, 122)
        val element123 =
            ElementModel("Ununpentium", "Uup", 115, ElementType.POST_TRANSITION_METAL, 123)
        val element124 =
            ElementModel("Ununhexium", "Uuh", 116, ElementType.POST_TRANSITION_METAL, 124)
        val element125 = ElementModel("Ununseptium", "Uus", 117, ElementType.HALOGEN, 125)
        val element126 = ElementModel("Ununoctium", "Uuo", 118, ElementType.NOBLE_GAS, 126)
        val element127 = EmptyModel(fullTableNumber = 127)
        val element128 = EmptyModel(fullTableNumber = 128)
        val element129 = EmptyModel(fullTableNumber = 129)
        val element130 = ElementModel("Lanthanum", "La", 57, ElementType.LANTHANIDE, 130)
        val element131 = ElementModel("Cerium", "Ce", 58, ElementType.LANTHANIDE, 131)
        val element132 = ElementModel("Praseodymium", "Pr", 59, ElementType.LANTHANIDE, 132)
        val element133 = ElementModel("Neodymium", "Nd", 60, ElementType.LANTHANIDE, 133)
        val element134 = ElementModel("Promethium", "Pm", 61, ElementType.LANTHANIDE, 134)
        val element135 = ElementModel("Samarium", "Sm", 62, ElementType.LANTHANIDE, 135)
        val element136 = ElementModel("Europium", "Eu", 63, ElementType.LANTHANIDE, 136)
        val element137 = ElementModel("Gadolinium", "Gd", 64, ElementType.LANTHANIDE, 137)
        val element138 = ElementModel("Terbium", "Tb", 65, ElementType.LANTHANIDE, 138)
        val element139 = ElementModel("Dysprosium", "Dy", 66, ElementType.LANTHANIDE, 139)
        val element140 = ElementModel("Holmium", "Ho", 67, ElementType.LANTHANIDE, 140)
        val element141 = ElementModel("Erbium", "Er", 68, ElementType.LANTHANIDE, 141)
        val element142 = ElementModel("Thulium", "Tm", 69, ElementType.LANTHANIDE, 142)
        val element143 = ElementModel("Ytterbium", "Yb", 70, ElementType.LANTHANIDE, 143)
        val element144 = ElementModel("Lutetium", "Lu", 71, ElementType.LANTHANIDE, 144)
        val element145 = EmptyModel(fullTableNumber = 145)
        val element146 = EmptyModel(fullTableNumber = 146)
        val element147 = EmptyModel(fullTableNumber = 147)
        val element148 = ElementModel("Actinium", "Ac", 89, ElementType.ACTINIDE, 149)
        val element149 = ElementModel("Thorium", "Th", 90, ElementType.ACTINIDE, 149)
        val element150 = ElementModel("Protactinium", "Pa", 91, ElementType.ACTINIDE, 150)
        val element151 = ElementModel("Uranium", "U", 92, ElementType.ACTINIDE, 151)
        val element152 = ElementModel("Neptunium", "Np", 93, ElementType.ACTINIDE, 152)
        val element153 = ElementModel("Plutonium", "Pu", 94, ElementType.ACTINIDE, 153)
        val element154 = ElementModel("Americium", "Am", 95, ElementType.ACTINIDE, 154)
        val element155 = ElementModel("Curium", "Cm", 96, ElementType.ACTINIDE, 155)
        val element156 = ElementModel("Berkelium", "Bk", 97, ElementType.ACTINIDE, 156)
        val element157 = ElementModel("Californium", "Cf", 98, ElementType.ACTINIDE, 157)
        val element158 = ElementModel("Einsteinium", "Es", 99, ElementType.ACTINIDE, 158)
        val element159 = ElementModel("Fermium", "Fm", 100, ElementType.ACTINIDE, 159)
        val element160 = ElementModel("Mendelevium", "Md", 101, ElementType.ACTINIDE, 160)
        val element161 = ElementModel("Nobelium", "No", 102, ElementType.ACTINIDE, 161)
        val element162 = ElementModel("Lawrencium", "Lr", 103, ElementType.ACTINIDE, 162)


        elementList.add(element1)
        elementList.add(element2)
        elementList.add(element3)
        elementList.add(element4)
        elementList.add(element5)
        elementList.add(element6)
        elementList.add(element7)
        elementList.add(element8)
        elementList.add(element9)
        elementList.add(element10)
        elementList.add(element11)
        elementList.add(element12)
        elementList.add(element13)
        elementList.add(element14)
        elementList.add(element15)
        elementList.add(element16)
        elementList.add(element17)
        elementList.add(element18)
        elementList.add(element19)
        elementList.add(element20)
        elementList.add(element21)
        elementList.add(element22)
        elementList.add(element23)
        elementList.add(element24)
        elementList.add(element25)
        elementList.add(element26)
        elementList.add(element27)
        elementList.add(element28)
        elementList.add(element29)
        elementList.add(element30)
        elementList.add(element31)
        elementList.add(element32)
        elementList.add(element33)
        elementList.add(element34)
        elementList.add(element35)
        elementList.add(element36)
        elementList.add(element37)
        elementList.add(element38)
        elementList.add(element39)
        elementList.add(element40)
        elementList.add(element41)
        elementList.add(element42)
        elementList.add(element43)
        elementList.add(element44)
        elementList.add(element45)
        elementList.add(element46)
        elementList.add(element47)
        elementList.add(element48)
        elementList.add(element49)
        elementList.add(element50)
        elementList.add(element51)
        elementList.add(element52)
        elementList.add(element53)
        elementList.add(element54)
        elementList.add(element55)
        elementList.add(element56)
        elementList.add(element57)
        elementList.add(element58)
        elementList.add(element59)
        elementList.add(element60)
        elementList.add(element61)
        elementList.add(element62)
        elementList.add(element63)
        elementList.add(element64)
        elementList.add(element65)
        elementList.add(element66)
        elementList.add(element67)
        elementList.add(element68)
        elementList.add(element69)
        elementList.add(element70)
        elementList.add(element71)
        elementList.add(element72)
        elementList.add(element73)
        elementList.add(element74)
        elementList.add(element75)
        elementList.add(element76)
        elementList.add(element77)
        elementList.add(element78)
        elementList.add(element79)
        elementList.add(element80)
        elementList.add(element81)
        elementList.add(element82)
        elementList.add(element83)
        elementList.add(element84)
        elementList.add(element85)
        elementList.add(element86)
        elementList.add(element87)
        elementList.add(element88)
        elementList.add(element89)
        elementList.add(element90)
        elementList.add(element91)
        elementList.add(element92)
        elementList.add(element93)
        elementList.add(element94)
        elementList.add(element95)
        elementList.add(element96)
        elementList.add(element97)
        elementList.add(element98)
        elementList.add(element99)
        elementList.add(element100)
        elementList.add(element101)
        elementList.add(element102)
        elementList.add(element103)
        elementList.add(element104)
        elementList.add(element105)
        elementList.add(element106)
        elementList.add(element107)
        elementList.add(element108)
        elementList.add(element109)
        elementList.add(element110)
        elementList.add(element111)
        elementList.add(element112)
        elementList.add(element113)
        elementList.add(element114)
        elementList.add(element115)
        elementList.add(element116)
        elementList.add(element117)
        elementList.add(element118)
        elementList.add(element119)
        elementList.add(element120)
        elementList.add(element121)
        elementList.add(element122)
        elementList.add(element123)
        elementList.add(element124)
        elementList.add(element125)
        elementList.add(element126)
        elementList.add(element127)
        elementList.add(element128)
        elementList.add(element129)
        elementList.add(element130)
        elementList.add(element131)
        elementList.add(element132)
        elementList.add(element133)
        elementList.add(element134)
        elementList.add(element135)
        elementList.add(element136)
        elementList.add(element137)
        elementList.add(element138)
        elementList.add(element139)
        elementList.add(element140)
        elementList.add(element141)
        elementList.add(element142)
        elementList.add(element143)
        elementList.add(element144)
        elementList.add(element145)
        elementList.add(element146)
        elementList.add(element147)
        elementList.add(element148)
        elementList.add(element149)
        elementList.add(element150)
        elementList.add(element151)
        elementList.add(element152)
        elementList.add(element153)
        elementList.add(element154)
        elementList.add(element155)
        elementList.add(element156)
        elementList.add(element157)
        elementList.add(element158)
        elementList.add(element159)
        elementList.add(element160)
        elementList.add(element161)
        elementList.add(element162)

        return elementList
    }

}