package com.canonal.periodictable

import com.canonal.periodictable.model.Element
import com.canonal.periodictable.model.ElementType

object Data {
    fun getDummyData(): List<Element> {
        //9x18=162 elements in full table
        //118 actual elements in periodic table
        //create 162 objects and set visibility property for non-element objects

        val elementList: ArrayList<Element> = arrayListOf()

        val element1 = Element("Hydrogen", "H", 1, ElementType.NONMETAL, 1,true)
        val element2 = Element(fullTableNumber = 2,isVisible = false)
        val element3 = Element(fullTableNumber = 3,isVisible = false)
        val element4 = Element(fullTableNumber = 4,isVisible = false)
        val element5 = Element(fullTableNumber = 5,isVisible = false)
        val element6 = Element(fullTableNumber = 6,isVisible = false)
        val element7 = Element(fullTableNumber = 7,isVisible = false)
        val element8 = Element(fullTableNumber = 8,isVisible = false)
        val element9 = Element(fullTableNumber = 9,isVisible = false)
        val element10 = Element(fullTableNumber = 10,isVisible = false)
        val element11 = Element(fullTableNumber = 11,isVisible = false)
        val element12 = Element(fullTableNumber = 12,isVisible = false)
        val element13 = Element(fullTableNumber = 13,isVisible = false)
        val element14 = Element(fullTableNumber = 14,isVisible = false)
        val element15 = Element(fullTableNumber = 15,isVisible = false)
        val element16 = Element(fullTableNumber = 16,isVisible = false)
        val element17 = Element(fullTableNumber = 17,isVisible = false)
        val element18 = Element("Helium", "He", 2, ElementType.NOBLE_GAS, 18,true)
        val element19 = Element("Lithium", "Li", 3, ElementType.ALKALI_METAL, 19,true)
        val element20 = Element("Beryllium", "Be", 4, ElementType.ALKALINE_EARTH_METAL, 20,true)
        val element21 = Element(fullTableNumber = 21,isVisible = false)
        val element22 = Element(fullTableNumber = 22,isVisible = false)
        val element23 = Element(fullTableNumber = 23,isVisible = false)
        val element24 = Element(fullTableNumber = 24,isVisible = false)
        val element25 = Element(fullTableNumber = 25,isVisible = false)
        val element26 = Element(fullTableNumber = 26,isVisible = false)
        val element27 = Element(fullTableNumber = 27,isVisible = false)
        val element28 = Element(fullTableNumber = 28,isVisible = false)
        val element29 = Element(fullTableNumber = 29,isVisible = false)
        val element30 =  Element(fullTableNumber =30,isVisible = false)
        val element31 = Element("Boron", "B", 5, ElementType.METALLOID, 31,true)
        val element32 = Element("Carbon", "C", 6, ElementType.NONMETAL, 32,true)
        val element33 = Element("Nitrogen", "N", 7, ElementType.NONMETAL, 33,true)
        val element34 = Element("Oxygen", "O", 8, ElementType.NONMETAL, 34,true)
        val element35 = Element("Fluorine", "F", 9, ElementType.HALOGEN, 35,true)
        val element36 = Element("Neon", "NE", 10, ElementType.NOBLE_GAS, 36,true)
        val element37 = Element("Sodium", "Na", 11, ElementType.ALKALI_METAL, 37,true)
        val element38 = Element("Magnesium", "Mg", 12, ElementType.ALKALINE_EARTH_METAL, 38,true)
        val element39 = Element(fullTableNumber = 39, isVisible = false)
        val element40 = Element(fullTableNumber = 40, isVisible = false)
        val element41 = Element(fullTableNumber = 41, isVisible = false)
        val element42 = Element(fullTableNumber = 42, isVisible = false)
        val element43 = Element(fullTableNumber = 43, isVisible = false)
        val element44 = Element(fullTableNumber = 44, isVisible = false)
        val element45 = Element(fullTableNumber = 45, isVisible = false)
        val element46 = Element(fullTableNumber = 46, isVisible = false)
        val element47 = Element(fullTableNumber = 47, isVisible = false)
        val element48 = Element(fullTableNumber = 48, isVisible = false)
        val element49 = Element("Aluminum", "Al", 13, ElementType.POST_TRANSITION_METAL, 49,true)
        val element50 = Element("Silicon", "Si", 14, ElementType.METALLOID, 50,true)
        val element51 = Element("Phosphorus", "P", 15, ElementType.NONMETAL, 51,true)
        val element52 = Element("Sulfur", "S", 16, ElementType.NONMETAL, 52,true)
        val element53 = Element("Chlorine", "Cl", 17, ElementType.HALOGEN, 53,true)
        val element54 = Element("Argon", "Ar", 18, ElementType.NOBLE_GAS, 54,true)
        val element55 = Element("Potassium", "K", 19, ElementType.ALKALI_METAL, 55,true)
        val element56 = Element("Calcium", "Ca", 20, ElementType.ALKALINE_EARTH_METAL, 56,true)
        val element57 = Element("Scandium", "Sc", 21, ElementType.TRANSITION_METAL, 57,true)
        val element58 = Element("Titanium", "Ti", 22, ElementType.TRANSITION_METAL, 58,true)
        val element59 = Element("Vanadium", "V", 23, ElementType.TRANSITION_METAL, 59,true)
        val element60 = Element("Chromium", "Cr", 24, ElementType.TRANSITION_METAL, 60,true)
        val element61 = Element("Manganese", "Mn", 25, ElementType.TRANSITION_METAL, 61,true)
        val element62 = Element("Iron", "Fe", 26, ElementType.TRANSITION_METAL, 62,true)
        val element63 = Element("Cobalt", "Co", 27, ElementType.TRANSITION_METAL, 63,true)
        val element64 = Element("Nickel", "Ni", 28, ElementType.TRANSITION_METAL, 64,true)
        val element65 = Element("Copper", "Cu", 29, ElementType.TRANSITION_METAL, 65,true)
        val element66 = Element("Zinc", "Zn", 30, ElementType.TRANSITION_METAL, 66,true)
        val element67 = Element("Gallium", "Ga", 31, ElementType.POST_TRANSITION_METAL, 67,true)
        val element68 = Element("Germanium", "Ge", 32, ElementType.METALLOID, 68,true)
        val element69 = Element("Arsenic", "As", 33, ElementType.METALLOID, 69,true)
        val element70 = Element("Selenium", "Se", 34, ElementType.NONMETAL, 70,true)
        val element71 = Element("Bromine", "Br", 35, ElementType.HALOGEN, 71,true)
        val element72 = Element("Krypton", "Kr", 36, ElementType.NOBLE_GAS, 72,true)
        val element73 = Element("Rubidium", "Rb", 37, ElementType.ALKALI_METAL, 73,true)
        val element74 = Element("Strontium", "Sr", 38, ElementType.ALKALINE_EARTH_METAL, 74,true)
        val element75 = Element("Yttrium", "Y", 39, ElementType.TRANSITION_METAL, 75,true)
        val element76 = Element("Zirconium", "Zr", 40, ElementType.TRANSITION_METAL, 76,true)
        val element77 = Element("Niobium", "Nb", 41, ElementType.TRANSITION_METAL, 77,true)
        val element78 = Element("Molybdenum", "Mo", 42, ElementType.TRANSITION_METAL, 78,true)
        val element79 = Element("Technetium", "Tc", 43, ElementType.TRANSITION_METAL, 79,true)
        val element80 = Element("Ruthenium", "Ru", 44, ElementType.TRANSITION_METAL, 80,true)
        val element81 = Element("Rhodium", "Rh", 45, ElementType.TRANSITION_METAL, 81,true)
        val element82 = Element("Palladium", "Pd", 46, ElementType.TRANSITION_METAL, 82,true)
        val element83 = Element("Silver", "Ag", 47, ElementType.TRANSITION_METAL, 83,true)
        val element84 = Element("Cadmium", "Cd", 48, ElementType.TRANSITION_METAL, 84,true)
        val element85 = Element("Indium", "In", 49, ElementType.POST_TRANSITION_METAL, 85,true)
        val element86 = Element("Tin", "Sn", 50, ElementType.POST_TRANSITION_METAL, 86,true)
        val element87 = Element("Antimony", "Sb", 51, ElementType.METALLOID, 87,true)
        val element88 = Element("Tellurium", "Te", 52, ElementType.METALLOID, 88,true)
        val element89 = Element("Iodine", "I", 53, ElementType.HALOGEN, 89,true)
        val element90 = Element("Xenon", "Xe", 54, ElementType.NOBLE_GAS, 90,true)
        val element91 = Element("Cesium", "Cs", 55, ElementType.ALKALI_METAL, 91,true)
        val element92 = Element("Barium", "Ba", 56, ElementType.ALKALINE_EARTH_METAL, 92,true)
        val element93 = Element(fullTableNumber = 93, isVisible = false)
        val element94 = Element("Hafnium", "Hf", 72, ElementType.TRANSITION_METAL, 94,true)
        val element95 = Element("Tantalum", "Ta", 73, ElementType.TRANSITION_METAL, 95,true)
        val element96 = Element("Tungsten", "W", 74, ElementType.TRANSITION_METAL, 96,true)
        val element97 = Element("Rhenium", "Re", 75, ElementType.TRANSITION_METAL, 97,true)
        val element98 = Element("Osmium", "Os", 76, ElementType.TRANSITION_METAL, 98,true)
        val element99 = Element("Iridium", "Ir", 77, ElementType.TRANSITION_METAL, 99,true)
        val element100 = Element("Platinum", "Pt", 78, ElementType.TRANSITION_METAL, 100,true)
        val element101 = Element("Gold", "Au", 79, ElementType.TRANSITION_METAL, 101,true)
        val element102 = Element("Mercury", "Hg", 80, ElementType.TRANSITION_METAL, 102,true)
        val element103 = Element("Thallium", "Tl", 81, ElementType.POST_TRANSITION_METAL, 103,true)
        val element104 = Element("Lead", "Pb", 82, ElementType.POST_TRANSITION_METAL, 104,true)
        val element105 = Element("Bismuth", "Bi", 83, ElementType.POST_TRANSITION_METAL, 105,true)
        val element106 = Element("Polonium", "Po", 84, ElementType.METALLOID, 106,true)
        val element107 = Element("Astatine", "At", 85, ElementType.HALOGEN, 107,true)
        val element108 = Element("Radon", "Rn", 86, ElementType.NOBLE_GAS, 108,true)
        val element109 = Element("Francium", "Fr", 87, ElementType.ALKALI_METAL, 109,true)
        val element110 = Element("Radium", "Ra", 88, ElementType.ALKALINE_EARTH_METAL, 110,true)
        val element111 = Element(fullTableNumber = 111, isVisible = false)
        val element112 = Element("Rutherfordium", "Rf", 104, ElementType.TRANSITION_METAL, 112,true)
        val element113 = Element("Dubnium", "Dd", 105, ElementType.TRANSITION_METAL, 113,true)
        val element114 = Element("Seaborgium", "Sg", 106, ElementType.TRANSITION_METAL, 114,true)
        val element115 = Element("Bohrium", "Bh", 107, ElementType.TRANSITION_METAL, 115,true)
        val element116 = Element("Hassium", "Hs", 108, ElementType.TRANSITION_METAL, 116,true)
        val element117 = Element("Meitnerium", "Mt", 109, ElementType.TRANSITION_METAL, 117,true)
        val element118 = Element("Darmstadtium", "Ds", 110, ElementType.TRANSITION_METAL, 118,true)
        val element119 = Element("Roentgenium", "Rg", 111, ElementType.TRANSITION_METAL, 119,true)
        val element120 = Element("Ununbium", "Uub", 112, ElementType.TRANSITION_METAL, 120,true)
        val element121 = Element("Ununtrium", "Uut", 113, ElementType.POST_TRANSITION_METAL, 121,true)
        val element122 = Element("Ununquadium", "Uuq", 114, ElementType.POST_TRANSITION_METAL, 122,true)
        val element123 = Element("Ununpentium", "Uup", 115, ElementType.POST_TRANSITION_METAL, 123,true)
        val element124 = Element("Ununhexium", "Uuh", 116, ElementType.POST_TRANSITION_METAL, 124,true)
        val element125 = Element("Ununseptium", "Uus", 117, ElementType.HALOGEN, 125,true)
        val element126 = Element("Ununoctium", "Uuo", 118, ElementType.NOBLE_GAS, 126,true)
        val element127 = Element(fullTableNumber = 127,isVisible = false)
        val element128 = Element(fullTableNumber = 128,isVisible = false)
        val element129 = Element(fullTableNumber = 129,isVisible = false)
        val element130 = Element("Lanthanum", "La", 57, ElementType.LANTHANIDE, 130,true)
        val element131 = Element("Cerium", "Ce", 58, ElementType.LANTHANIDE, 131,true)
        val element132 = Element("Praseodymium", "Pr", 59, ElementType.LANTHANIDE, 132,true)
        val element133 = Element("Neodymium", "Nd", 60, ElementType.LANTHANIDE, 133,true)
        val element134 = Element("Promethium", "Pm", 61, ElementType.LANTHANIDE, 134,true)
        val element135 = Element("Samarium", "Sm", 62, ElementType.LANTHANIDE, 135,true)
        val element136 = Element("Europium", "Eu", 63, ElementType.LANTHANIDE, 136,true)
        val element137 = Element("Gadolinium", "Gd", 64, ElementType.LANTHANIDE, 137,true)
        val element138 = Element("Terbium", "Tb", 65, ElementType.LANTHANIDE, 138,true)
        val element139 = Element("Dysprosium", "Dy", 66, ElementType.LANTHANIDE, 139,true)
        val element140 = Element("Holmium", "Ho", 67, ElementType.LANTHANIDE, 140,true)
        val element141 = Element("Erbium", "Er", 68, ElementType.LANTHANIDE, 141,true)
        val element142 = Element("Thulium", "Tm", 69, ElementType.LANTHANIDE, 142,true)
        val element143 = Element("Ytterbium", "Yb", 70, ElementType.LANTHANIDE, 143,true)
        val element144 = Element("Lutetium", "Lu", 71, ElementType.LANTHANIDE, 144,true)
        val element145 = Element(fullTableNumber = 145,isVisible = false)
        val element146 = Element(fullTableNumber = 146,isVisible = false)
        val element147 = Element(fullTableNumber = 147,isVisible = false)
        val element148 = Element("Actinium", "Ac", 89, ElementType.ACTINIDE, 149,true)
        val element149 = Element("Thorium", "Th", 90, ElementType.ACTINIDE, 149,true)
        val element150 = Element("Protactinium", "Pa", 91, ElementType.ACTINIDE, 150,true)
        val element151 = Element("Uranium", "U", 92, ElementType.ACTINIDE, 151,true)
        val element152 = Element("Neptunium", "Np", 93, ElementType.ACTINIDE, 152,true)
        val element153 = Element("Plutonium", "Pu", 94, ElementType.ACTINIDE, 153,true)
        val element154 = Element("Americium", "Am", 95, ElementType.ACTINIDE, 154,true)
        val element155 = Element("Curium", "Cm", 96, ElementType.ACTINIDE, 155,true)
        val element156 = Element("Berkelium", "Bk", 97, ElementType.ACTINIDE, 156,true)
        val element157 = Element("Californium", "Cf", 98, ElementType.ACTINIDE, 157,true)
        val element158 = Element("Einsteinium", "Es", 99, ElementType.ACTINIDE, 158,true)
        val element159 = Element("Fermium", "Fm", 100, ElementType.ACTINIDE, 159,true)
        val element160 = Element("Mendelevium", "Md", 101, ElementType.ACTINIDE, 160,true)
        val element161 = Element("Nobelium", "No", 102, ElementType.ACTINIDE, 161,true)
        val element162 = Element("Lawrencium", "Lr", 103, ElementType.ACTINIDE, 162,true)


        elementList.add(element1)
        elementList.add(element2)
        elementList.add(element3)
        elementList.add(element4)
        elementList.add(element5)
        elementList.add(element6)
        elementList.add(element7)
        elementList.add(element8)
        elementList.add(element9)
        elementList.add(element10)
        elementList.add(element11)
        elementList.add(element12)
        elementList.add(element13)
        elementList.add(element14)
        elementList.add(element15)
        elementList.add(element16)
        elementList.add(element17)
        elementList.add(element18)
        elementList.add(element19)
        elementList.add(element20)
        elementList.add(element21)
        elementList.add(element22)
        elementList.add(element23)
        elementList.add(element24)
        elementList.add(element25)
        elementList.add(element26)
        elementList.add(element27)
        elementList.add(element28)
        elementList.add(element29)
        elementList.add(element30)
        elementList.add(element31)
        elementList.add(element32)
        elementList.add(element33)
        elementList.add(element34)
        elementList.add(element35)
        elementList.add(element36)
        elementList.add(element37)
        elementList.add(element38)
        elementList.add(element39)
        elementList.add(element40)
        elementList.add(element41)
        elementList.add(element42)
        elementList.add(element43)
        elementList.add(element44)
        elementList.add(element45)
        elementList.add(element46)
        elementList.add(element47)
        elementList.add(element48)
        elementList.add(element49)
        elementList.add(element50)
        elementList.add(element51)
        elementList.add(element52)
        elementList.add(element53)
        elementList.add(element54)
        elementList.add(element55)
        elementList.add(element56)
        elementList.add(element57)
        elementList.add(element58)
        elementList.add(element59)
        elementList.add(element60)
        elementList.add(element61)
        elementList.add(element62)
        elementList.add(element63)
        elementList.add(element64)
        elementList.add(element65)
        elementList.add(element66)
        elementList.add(element67)
        elementList.add(element68)
        elementList.add(element69)
        elementList.add(element70)
        elementList.add(element71)
        elementList.add(element72)
        elementList.add(element73)
        elementList.add(element74)
        elementList.add(element75)
        elementList.add(element76)
        elementList.add(element77)
        elementList.add(element78)
        elementList.add(element79)
        elementList.add(element80)
        elementList.add(element81)
        elementList.add(element82)
        elementList.add(element83)
        elementList.add(element84)
        elementList.add(element85)
        elementList.add(element86)
        elementList.add(element87)
        elementList.add(element88)
        elementList.add(element89)
        elementList.add(element90)
        elementList.add(element91)
        elementList.add(element92)
        elementList.add(element93)
        elementList.add(element94)
        elementList.add(element95)
        elementList.add(element96)
        elementList.add(element97)
        elementList.add(element98)
        elementList.add(element99)
        elementList.add(element100)
        elementList.add(element101)
        elementList.add(element102)
        elementList.add(element103)
        elementList.add(element104)
        elementList.add(element105)
        elementList.add(element106)
        elementList.add(element107)
        elementList.add(element108)
        elementList.add(element109)
        elementList.add(element110)
        elementList.add(element111)
        elementList.add(element112)
        elementList.add(element113)
        elementList.add(element114)
        elementList.add(element115)
        elementList.add(element116)
        elementList.add(element117)
        elementList.add(element118)
        elementList.add(element119)
        elementList.add(element120)
        elementList.add(element121)
        elementList.add(element122)
        elementList.add(element123)
        elementList.add(element124)
        elementList.add(element125)
        elementList.add(element126)
        elementList.add(element127)
        elementList.add(element128)
        elementList.add(element129)
        elementList.add(element130)
        elementList.add(element131)
        elementList.add(element132)
        elementList.add(element133)
        elementList.add(element134)
        elementList.add(element135)
        elementList.add(element136)
        elementList.add(element137)
        elementList.add(element138)
        elementList.add(element139)
        elementList.add(element140)
        elementList.add(element141)
        elementList.add(element142)
        elementList.add(element143)
        elementList.add(element144)
        elementList.add(element145)
        elementList.add(element146)
        elementList.add(element147)
        elementList.add(element148)
        elementList.add(element149)
        elementList.add(element150)
        elementList.add(element151)
        elementList.add(element152)
        elementList.add(element153)
        elementList.add(element154)
        elementList.add(element155)
        elementList.add(element156)
        elementList.add(element157)
        elementList.add(element158)
        elementList.add(element159)
        elementList.add(element160)
        elementList.add(element161)
        elementList.add(element162)

        return elementList
    }
}